### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by scholery**
When I install the novaclinet,there were some errors caused by olso,so upgrade the olso's version to fix these errors.

### CODE REVIEW

**Comment by kei-** [comment]
Could you merge the commits into Tag 2.20.0 ?

**Comment by scholery** [comment]
Can't merge the commits to tag 2.20.0.It just can merge to master or branch.

**Comment by kei-** [comment]
Please create the branch from tag 2.20.0, and merge.

**Comment by kei-** [comment]
create branch 2.20.0-2

**Pull request closed without merging**
